import { useState } from "react";
import "./BacklinkChecker.css";

interface Backlink {
  referringDomain: string;
  backlinkUrl: string;
  targetPage: string;
  anchorText: string;
  nofollow: boolean;
  firstSeen: string;
  rating: "good" | "warning" | "bad";
  reasons: string[];
}

interface BacklinkResult {
  domain: string;
  summary: {
    total: number;
    good: number;
    warning: number;
    bad: number;
    uniqueDomains: number;
  };
  backlinks: Backlink[];
  isDemo: boolean;
}

const PRO_FEATURES = [
  { title: "Full Backlink List", desc: "See every backlink pointing to your site, not just the top 5." },
  { title: "Toxic Backlink Report", desc: "Identify harmful links that could trigger Google penalties." },
  { title: "New / Lost Backlinks", desc: "Track which backlinks you've gained or lost over time." },
  { title: "Anchor Text Analysis", desc: "See your anchor text distribution and over-optimization risks." },
  { title: "Referring Domain Quality", desc: "Domain authority, trust score, and spam ratings for each referrer." },
  { title: "AI Cleanup Plan", desc: "Get a step-by-step disavow plan generated by AI to clean your profile." },
];

export default function BacklinkChecker() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<BacklinkResult | null>(null);

  async function handleCheck() {
    if (!url.trim()) return;
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const res = await fetch("/api/backlinks/check", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim() }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Error ${res.status}`);
      }
      setResult(await res.json());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to check backlinks.");
    } finally {
      setLoading(false);
    }
  }

  const freeLinks = result ? result.backlinks.slice(0, 5) : [];

  return (
    <div className="bl">
      {/* Nav */}
      <nav className="bl-nav">
        <div className="bl-wrap">
          <a href="/" className="bl-nav__logo">SEO Rank Writer</a>
          <div className="bl-nav__links">
            <a href="/app">Open App</a>
            <a href="/plugins">Plugin</a>
            <a href="/">Home</a>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="bl-hero">
        <div className="bl-wrap">
          <div className="bl-hero__badge">Free Tool</div>
          <h1 className="bl-hero__h1">Backlink Checker</h1>
          <p className="bl-hero__sub">
            Check any website's backlink profile. Find toxic links, quality referrers, and anchor text issues.
          </p>

          <div className="bl-input-row">
            <input
              type="text"
              className="bl-input"
              placeholder="Enter domain or URL (e.g. example.com)"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleCheck()}
            />
            <button
              className="bl-check-btn"
              onClick={handleCheck}
              disabled={!url.trim() || loading}
            >
              {loading ? "Checking..." : "Check Backlinks"}
            </button>
          </div>

          {error && <div className="bl-error">{error}</div>}
        </div>
      </section>

      {/* Results */}
      {result && (
        <section className="bl-results">
          <div className="bl-wrap">

            {/* Summary */}
            <div className="bl-summary">
              <div className="bl-summary-card">
                <div className="bl-summary-val">{result.summary.total}</div>
                <div className="bl-summary-label">Total Backlinks</div>
              </div>
              <div className="bl-summary-card">
                <div className="bl-summary-val bl-summary-val--domains">{result.summary.uniqueDomains}</div>
                <div className="bl-summary-label">Referring Domains</div>
              </div>
              <div className="bl-summary-card">
                <div className="bl-summary-val bl-summary-val--good">{result.summary.good}</div>
                <div className="bl-summary-label">Good</div>
              </div>
              <div className="bl-summary-card">
                <div className="bl-summary-val bl-summary-val--warn">{result.summary.warning}</div>
                <div className="bl-summary-label">Warning</div>
              </div>
              <div className="bl-summary-card">
                <div className="bl-summary-val bl-summary-val--bad">{result.summary.bad}</div>
                <div className="bl-summary-label">Toxic</div>
              </div>
            </div>

            {result.isDemo && (
              <div className="bl-demo-notice">
                Showing demo data. Connect a backlink API provider for real results.
              </div>
            )}

            {/* Free backlinks (top 5) */}
            <h2 className="bl-section-title">Top Backlinks for {result.domain}</h2>
            <div className="bl-links">
              {freeLinks.map((link, i) => (
                <div key={i} className="bl-link-card">
                  <div className="bl-link-header">
                    <span className={`bl-rating bl-rating--${link.rating}`}>
                      {link.rating === "good" ? "Good" : link.rating === "warning" ? "Warning" : "Toxic"}
                    </span>
                    <span className="bl-link-domain">{link.referringDomain}</span>
                    {link.nofollow && <span className="bl-nofollow">nofollow</span>}
                  </div>
                  <div className="bl-link-body">
                    <div className="bl-link-row">
                      <span className="bl-link-label">Source</span>
                      <span className="bl-link-val bl-link-val--url" title={link.backlinkUrl}>
                        {link.backlinkUrl.length > 60 ? link.backlinkUrl.slice(0, 60) + "..." : link.backlinkUrl}
                      </span>
                    </div>
                    <div className="bl-link-row">
                      <span className="bl-link-label">Target</span>
                      <span className="bl-link-val">{link.targetPage}</span>
                    </div>
                    <div className="bl-link-row">
                      <span className="bl-link-label">Anchor</span>
                      <span className="bl-link-val bl-link-val--anchor">"{link.anchorText}"</span>
                    </div>
                    <div className="bl-link-row">
                      <span className="bl-link-label">Reason</span>
                      <span className="bl-link-val">{link.reasons.join(" · ")}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Locked Pro Section */}
            <div className="bl-pro-section">
              <div className="bl-pro-overlay">
                <div className="bl-pro-lock">
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="3" y="11" width="18" height="11" rx="2" />
                    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                  </svg>
                </div>
                <h3 className="bl-pro-title">Unlock Full Backlink Report with Pro</h3>
                <p className="bl-pro-desc">
                  Get the complete backlink analysis with toxic link detection, anchor text distribution, and an AI-generated cleanup plan.
                </p>
                <a href="/plugins" className="bl-pro-cta">Upgrade to Pro</a>
              </div>

              <div className="bl-pro-cards">
                {PRO_FEATURES.map((f, i) => (
                  <div key={i} className="bl-pro-card">
                    <h4 className="bl-pro-card__title">{f.title}</h4>
                    <p className="bl-pro-card__desc">{f.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
      )}

      {/* Footer */}
      <footer className="bl-footer">
        <div className="bl-wrap">
          <span className="bl-footer__brand">SEO Rank Writer</span>
          <span className="bl-footer__text">Generate. Publish. Rank.</span>
        </div>
      </footer>
    </div>
  );
}
